export { Getstarted } from "./splashscreen/Getstarted";
export { Language } from "./language/Language";
export { default as Register } from "./register/Register";
export { default as SignIn } from "./register/SignIn/SignIn";
export { default as SignUp } from "./register/SignUp/SignUp";
export { PoliceDetail } from "./register/police/detail/PoliceDetail";
export { DetailFilled } from "./register/police/detailfilled/DetailFilled";
export { Home } from "./homescreen/Home";
export { Profile } from "./profile/Profile";
export { EditProfile } from "./profile/EditProfile";
export { ViewProfile } from "./profile/ViewProfile";
export { Post } from "./postscreen/Post";
export { CyberCrime } from "./postscreen/CyberCrime";
export { MissingPerson } from "./postscreen/MissingPerson";
export { MSLF } from "./postscreen/MSLF";
export { Wanted } from "./postscreen/Wanted";
export { UnidPerson } from "./postscreen/UnidPerson";
export { AllComplaints } from "./postscreen/AllComplaints";
export { Exam } from "./profile/Exam";
// export { Complaints } from "./homescreen/Complaints";
export { ComplaintGroup } from "./homescreen/ComplaintGroup";
export { ComplaintsLayout } from "./homescreen/ComplaintsLayout";
export { Setting } from "./profile/Setting";
export { Help } from "./profile/Help";
