export { Getstarted } from "./splashscreen/Getstarted";
export { Language } from "./language/Language";
export { default as Register } from "./register/Register";
export { PoliceSignin } from "./register/police/signin/PoliceSignin";
export { PoliceSignup } from "./register/police/signup/PoliceSignup";
export { CitizenSignin } from "./register/citizen/signin/CitizenSignin";
export { CitizenSignup } from "./register/citizen/signup/CitizenSignup";
export { default as SignIn } from "./register/SignIn/SignIn";
export { default as SignUp } from "./register/SignUp/SignUp";
export { PoliceDetail } from "./register/police/detail/PoliceDetail";
export { DetailFilled } from "./register/police/detailfilled/DetailFilled";
export { Home } from "./homescreen/Home";
export { Profile } from "./profile/Profile";
export { EditProfile } from "./profile/EditProfile";
export { Post } from "./postscreen/Post";
export { Complaints } from "./homescreen/Complaints";
export { ComplaintGroup } from "./homescreen/ComplaintGroup";
export { Setting } from "./profile/Setting";
export { Help } from "./profile/Help";
